// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6YQHETRrCRhA9zUyfpv6ayGe1hQgBRM',
    appId: '1:412911318801:web:adbace53155cae7cd8beb0',
    messagingSenderId: '412911318801',
    projectId: 'jobsearch-329c0',
    authDomain: 'jobsearch-329c0.firebaseapp.com',
    storageBucket: 'jobsearch-329c0.appspot.com',
    measurementId: 'G-0KKQMCL1YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0CAkm_y3naHIUxYQZHNfeoq49ZISs1s',
    appId: '1:412911318801:android:677ed495fe5416b0d8beb0',
    messagingSenderId: '412911318801',
    projectId: 'jobsearch-329c0',
    storageBucket: 'jobsearch-329c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKl8MV6u686db5bd_V9ZpwZPyHPGB2ekw',
    appId: '1:412911318801:ios:59a8aab8883f137ed8beb0',
    messagingSenderId: '412911318801',
    projectId: 'jobsearch-329c0',
    storageBucket: 'jobsearch-329c0.appspot.com',
    iosBundleId: 'com.example.jobSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKl8MV6u686db5bd_V9ZpwZPyHPGB2ekw',
    appId: '1:412911318801:ios:8879a764b86e2ec9d8beb0',
    messagingSenderId: '412911318801',
    projectId: 'jobsearch-329c0',
    storageBucket: 'jobsearch-329c0.appspot.com',
    iosBundleId: 'com.example.jobSearch.RunnerTests',
  );
}
